// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Bread struct {
	ID        string     `json:"id"`
	BreadInfo *BreadInfo `json:"breadInfo"`
}

type BreadInfo struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}

type Query struct {
}
